### ISSUE TITLE
how to configure Server Components

### ISSUE THREAD

**Issue by astutesixface** [givanz/VvvebJs#141]
Hi,
Till now it's look great!!!
Unfortunately it seems that when dragging and dropping a server component block it's not working.
can you tell me how to configure the components?
please and thanks for your help..
Regards,

**Comment by astutesixface** [comment]
when i drag and drop i get the error

 cannot call methods on button prior to initialization; attempted to call method 'toggle'
DOMException: Failed to execute 'insertBefore' on 'Node': The new child element contains the parent.
    at HTMLTextAreaElement.<anonymous> (http://localhost/VvvebJs-master/js/jquery.min.js:2:48827)
    at Re (http://localhost/VvvebJs-master/js/jquery.min.js:2:47076)
    at w.fn.init.prepend (http://localhost/VvvebJs-master/js/jquery.min.js:2:48717)
    at w.fn.init.w.fn.<computed> [as prependTo] (http://localhost/VvvebJs-master/js/jquery.min.js:2:50106)
    at HTMLHtmlElement.<anonymous> (http://localhost/VvvebJs-master/libs/builder/builder.js:873:54)
    at HTMLHtmlElement.dispatch (http://localhost/VvvebJs-master/js/jquery.min.js:2:41772)
    at HTMLHtmlElement.y.handle (http://localhost/VvvebJs-master/js/jquery.min.js:2:39791)


Uncaught Error: cannot call methods on button prior to initialization; attempted to call method 'toggle'
    at Function.error (jquery.min.js:2)
    at HTMLLabelElement.<anonymous> (jquery.autocomplete.js:6)
    at Function.each (jquery.min.js:2)
    at w.fn.init.each (jquery.min.js:2)
    at w.fn.init.t.fn.<computed> (jquery.autocomplete.js:6)
    at w.fn.init.button (jquery.autocomplete.js:10)
    at Object.setValue (inputs.js:353)
    at Object.render (builder.js:415)
    at Object.loadNodeComponent (builder.js:790)
    at HTMLHtmlElement.<anonymous> (builder.js:949)

**Comment by assadnazar** [comment]
Anyone?
