### ISSUE TITLE
Admin panel access

### ISSUE THREAD

**Issue by Blitzshadow** [givanz/VvvebJs#227]
Hello, I know it's kind of dumb questions, but how can I access Admin Panel ? Thanks for help

**Comment by Bocon778** [comment]
open the editor.html file or go to https://example.com/editor.html

**Comment by Blitzshadow** [comment]
Yes im opening editor.html and the editor works fine, I just dont see this CMS vertical admin panel with "shop" module dashboard etc. How to solve this ? If you could help me i would be very thankfull

**Comment by Blitzshadow** [comment]
When im trying to acess localhost/admin/   i'm getting such error

Fatal error: Uncaught Exception: Access denied for user 'root'@'localhost' (using password: YES) in C:\xampp\htdocs\system\db\mysqli.php:112 Stack trace: #0 C:\xampp\htdocs\admin\model\languagessql.php(27): Vvveb\System\Db\Mysqli->__construct() #1 C:\xampp\htdocs\admin\controller\base.php(63): Vvveb\Sql\languagesSQL->__construct() #2 C:\xampp\htdocs\system\frontcontroller.php(99): Vvveb\Controller\Base->__construct() #3 C:\xampp\htdocs\system\startup.php(172): Vvveb\System\FrontController::notFound(false, 500, Array) #4 [internal function]: Vvveb\System\exceptionHandler(Object(Exception)) #5 {main} thrown in C:\xampp\htdocs\system\db\mysqli.php on line 112

**Comment by Blitzshadow** [comment]
Now im using ampps and got only such error:

Notice: Undefined index: count in C:\Program Files\Ampps\www\storage\compiled-templates\app_blog-default_error500.html on line 89

The site is experiencing some dificulties, please try again, if the problem still persists please contact support.
Error

Class 'Vvveb\Sql\PostsSQL' not found
File

C:\Program Files\Ampps\www\app\component\posts.php51
Code

	public $options = [];


	function __construct($options) {

		return parent::__construct($options);

	}


	function results() {

		$posts = new \Vvveb\Sql\PostsSQL();


		if ($page = $this->options['page']) {

			$this->options['start'] = ($page - 1) * $this->options['limit'];

		}


		if (isset($this->options['post_id']) && is_array($this->options['post_id']) && $this->options['source'] == 'autocomplete') {

**Comment by Blitzshadow** [comment]
Warning: Use of undefined constant DIR_SQL - assumed 'DIR_SQL' (this will throw an Error in a future version of PHP) in C:\Program Files\Ampps\www\system\startup.php on line 103

Warning: filemtime(): stat failed for DIR_SQLposts.sql in C:\Program Files\Ampps\www\system\startup.php on line 107

Warning: Use of undefined constant DB_HOST - assumed 'DB_HOST' (this will throw an Error in a future version of PHP) in C:\Program Files\Ampps\www\system\db\mysqli.php on line 97

Warning: Use of undefined constant DB_NAME - assumed 'DB_NAME' (this will throw an Error in a future version of PHP) in C:\Program Files\Ampps\www\system\db\mysqli.php on line 97

Warning: Use of undefined constant DB_USER - assumed 'DB_USER' (this will throw an Error in a future version of PHP) in C:\Program Files\Ampps\www\system\db\mysqli.php on line 97

Warning: Use of undefined constant DB_PASS - assumed 'DB_PASS' (this will throw an Error in a future version of PHP) in C:\Program Files\Ampps\www\system\db\mysqli.php on line 97

Warning: Use of undefined constant DB_PREFIX - assumed 'DB_PREFIX' (this will throw an Error in a future version of PHP) in C:\Program Files\Ampps\www\system\db\mysqli.php on line 97

Warning: mysqli::__construct(): php_network_getaddresses: getaddrinfo failed: No such host is known. in C:\Program Files\Ampps\www\system\db\mysqli.php on line 108

**Comment by givanz** [comment]
Hi

Currently Vvveb CMS is under development and not yet ready for public use when the code will reach a stable point it will be published on https://github.com/givanz/Vvveb

From the error message `Access denied for user 'root'@'localhost' (using password: YES) ` it seems that the database credentials are wrong.
