### ISSUE TITLE
Unable to get the app, started on NodeJS 18

### ISSUE THREAD

**Issue by Techrone** [givanz/VvvebJs#297]
Hi,

I have recently installed NodeJS 18 LTS on a clean windows install and I was unable to run the command `npm i` to install gulp and missing packages. As it produces a lot of errors and I am uncertain what may be the cause of. 

Console log:
PS D:\Development\Website builder\VvvebJs> npm i
npm WARN old lockfile
npm WARN old lockfile The package-lock.json file was created with an old version of npm,
npm WARN old lockfile so supplemental metadata must be fetched from the registry.
npm WARN old lockfile
npm WARN old lockfile This is a one-time fix-up, please be patient...
npm WARN old lockfile
npm WARN old lockfile Error: Integrity checksum failed when using sha512: wanted sha512-f/wzC2QaWBs7t9IYqB4T3sR1xviIViXJRJTWBlx2Gf3g0Xi5vI7Yy4koXQ1c9OYDGHN9sBy1DQ2AB8fqZBWhUg== but got sha512-aXpmwoOhRBrw6X3j0h5RloK4x1OzsxMPyxqIHyNfSe2pypkVTZFpEiRoSipPEPlMrh0HW/XsjkJ5WgnCirpNUw==.
npm WARN old lockfile     at RegistryFetcher.manifest (C:\Program Files\nodejs\node_modules\npm\node_modules\pacote\lib\registry.js:146:35)
npm WARN old lockfile     at async Array.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\@npmcli\arborist\lib\arborist\build-ideal-tree.js:734:24)
npm WARN old lockfile  Could not fetch metadata for hosted-git-info@3.0.8 Error: Integrity checksum failed when using sha512: wanted sha512-f/wzC2QaWBs7t9IYqB4T3sR1xviIViXJRJTWBlx2Gf3g0Xi5vI7Yy4koXQ1c9OYDGHN9sBy1DQ2AB8fqZBWhUg== but got sha512-aXpmwoOhRBrw6X3j0h5RloK4x1OzsxMPyxqIHyNfSe2pypkVTZFpEiRoSipPEPlMrh0HW/XsjkJ5WgnCirpNUw==.
npm WARN old lockfile     at RegistryFetcher.manifest (C:\Program Files\nodejs\node_modules\npm\node_modules\pacote\lib\registry.js:146:35)
npm WARN old lockfile     at async Array.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\@npmcli\arborist\lib\arborist\build-ideal-tree.js:734:24) {
npm WARN old lockfile   code: 'EINTEGRITY'
npm WARN old lockfile }
npm WARN deprecated source-map-url@0.4.1: See https://github.com/lydell/source-map-url#deprecated
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated source-map-resolve@0.5.3: See https://github.com/lydell/source-map-resolve#deprecated
npm WARN deprecated chokidar@2.1.8: Chokidar 2 does not receive security updates since 2019. Upgrade to chokidar 3 with 15x fewer dependencies
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated tar@2.2.2: This version of tar is no longer supported, and will not receive security updates. Please upgrade asap.
npm ERR! code 1
npm ERR! path D:\Development\Website builder\VvvebJs\node_modules\node-sass
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c node scripts/build.js
npm ERR! Building: C:\Program Files\nodejs\node.exe D:\Development\Website builder\VvvebJs\node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp verb cli [
npm ERR! gyp verb cli   'C:\\Program Files\\nodejs\\node.exe',
npm ERR! gyp verb cli   'D:\\Development\\Website builder\\VvvebJs\\node_modules\\node-gyp\\bin\\node-gyp.js',
npm ERR! gyp verb cli   'rebuild',
npm ERR! gyp verb cli   '--verbose',
npm ERR! gyp verb cli   '--libsass_ext=',
npm ERR! gyp verb cli   '--libsass_cflags=',
npm ERR! gyp verb cli   '--libsass_ldflags=',
npm ERR! gyp verb cli   '--libsass_library='
npm ERR! gyp verb cli ]
npm ERR! gyp info using node-gyp@3.8.0
npm ERR! gyp info using node@18.15.0 | win32 | x64
npm ERR! gyp verb command rebuild []
npm ERR! gyp verb command clean []
npm ERR! gyp verb clean removing "build" directory
npm ERR! gyp verb command configure []
npm ERR! gyp verb check python checking for Python executable "python2" in the PATH
npm ERR! gyp verb `which` failed Error: not found: python2
npm ERR! gyp verb `which` failed     at getNotFoundError (D:\Development\Website builder\VvvebJs\node_modules\which\which.js:13:12)
npm ERR! gyp verb `which` failed     at F (D:\Development\Website builder\VvvebJs\node_modules\which\which.js:68:19)
npm ERR! gyp verb `which` failed     at E (D:\Development\Website builder\VvvebJs\node_modules\which\which.js:80:29)
npm ERR! gyp verb `which` failed     at D:\Development\Website builder\VvvebJs\node_modules\which\which.js:89:16
npm ERR! gyp verb `which` failed     at D:\Development\Website builder\VvvebJs\node_modules\isexe\index.js:42:5
npm ERR! gyp verb `which` failed     at D:\Development\Website builder\VvvebJs\node_modules\isexe\windows.js:36:5
npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:208:21)
npm ERR! gyp verb `which` failed  python2 Error: not found: python2
npm ERR! gyp verb `which` failed     at getNotFoundError (D:\Development\Website builder\VvvebJs\node_modules\which\which.js:13:12)
npm ERR! gyp verb `which` failed     at F (D:\Development\Website builder\VvvebJs\node_modules\which\which.js:68:19)
npm ERR! gyp verb `which` failed     at E (D:\Development\Website builder\VvvebJs\node_modules\which\which.js:80:29)
npm ERR! gyp verb `which` failed     at D:\Development\Website builder\VvvebJs\node_modules\which\which.js:89:16
npm ERR! gyp verb `which` failed     at D:\Development\Website builder\VvvebJs\node_modules\isexe\index.js:42:5
npm ERR! gyp verb `which` failed     at D:\Development\Website builder\VvvebJs\node_modules\isexe\windows.js:36:5
npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:208:21) {
npm ERR! gyp verb `which` failed   code: 'ENOENT'
npm ERR! gyp verb `which` failed }
npm ERR! gyp verb check python checking for Python executable "python" in the PATH
npm ERR! gyp verb `which` failed Error: not found: python
npm ERR! gyp verb `which` failed     at getNotFoundError (D:\Development\Website builder\VvvebJs\node_modules\which\which.js:13:12)
npm ERR! gyp verb `which` failed     at F (D:\Development\Website builder\VvvebJs\node_modules\which\which.js:68:19)
npm ERR! gyp verb `which` failed     at E (D:\Development\Website builder\VvvebJs\node_modules\which\which.js:80:29)
npm ERR! gyp verb `which` failed     at D:\Development\Website builder\VvvebJs\node_modules\which\which.js:89:16
npm ERR! gyp verb `which` failed     at D:\Development\Website builder\VvvebJs\node_modules\isexe\index.js:42:5
npm ERR! gyp verb `which` failed     at D:\Development\Website builder\VvvebJs\node_modules\isexe\windows.js:36:5
npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:208:21)
npm ERR! gyp verb `which` failed  python Error: not found: python
npm ERR! gyp verb `which` failed     at getNotFoundError (D:\Development\Website builder\VvvebJs\node_modules\which\which.js:13:12)
npm ERR! gyp verb `which` failed     at F (D:\Development\Website builder\VvvebJs\node_modules\which\which.js:68:19)
npm ERR! gyp verb `which` failed     at E (D:\Development\Website builder\VvvebJs\node_modules\which\which.js:80:29)
npm ERR! gyp verb `which` failed     at D:\Development\Website builder\VvvebJs\node_modules\which\which.js:89:16
npm ERR! gyp verb `which` failed     at D:\Development\Website builder\VvvebJs\node_modules\isexe\index.js:42:5
npm ERR! gyp verb `which` failed     at D:\Development\Website builder\VvvebJs\node_modules\isexe\windows.js:36:5
npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:208:21) {
npm ERR! gyp verb `which` failed   code: 'ENOENT'
npm ERR! gyp verb `which` failed }
npm ERR! gyp verb could not find "python". checking python launcher
npm ERR! gyp verb could not find "python". guessing location
npm ERR! gyp verb ensuring that file exists: C:\Python27\python.exe
npm ERR! gyp ERR! configure error
npm ERR! gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
npm ERR! gyp ERR! stack     at PythonFinder.failNoPython (D:\Development\Website builder\VvvebJs\node_modules\node-gyp\lib\configure.js:484:19)
npm ERR! gyp ERR! stack     at PythonFinder.<anonymous> (D:\Development\Website builder\VvvebJs\node_modules\node-gyp\lib\configure.js:509:16)
npm ERR! gyp ERR! stack     at callback (D:\Development\Website builder\VvvebJs\node_modules\graceful-fs\polyfills.js:296:20)
npm ERR! gyp ERR! stack     at FSReqCallback.oncomplete (node:fs:208:21)
npm ERR! gyp ERR! System Windows_NT 10.0.19045
npm ERR! gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "D:\\Development\\Website builder\\VvvebJs\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
npm ERR! gyp ERR! cwd D:\Development\Website builder\VvvebJs\node_modules\node-sass
npm ERR! gyp ERR! node -v v18.15.0
npm ERR! gyp ERR! node-gyp -v v3.8.0
npm ERR! gyp ERR! not ok
npm ERR! Build failed with error code: 1

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\{User}\AppData\Local\npm-cache\_logs\2023-03-13T17_01_44_845Z-debug-0.log

**Comment by givanz** [comment]
Hi

Can you please delete `package-lock.json` and run `npm i` again?

**Comment by Techrone** [comment]
The same error still occurred.

PS D:\Development\Website builder\VvvebJs> npm i
npm WARN deprecated source-map-url@0.4.1: See https://github.com/lydell/source-map-url#deprecated
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated source-map-resolve@0.5.3: See https://github.com/lydell/source-map-resolve#deprecated
npm WARN deprecated chokidar@2.1.8: Chokidar 2 does not receive security updates since 2019. Upgrade to chokidar 3 with 15x fewer dependencies
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated tar@2.2.2: This version of tar is no longer supported, and will not receive security updates. Please upgrade asap.
npm ERR! code 1
npm ERR! path D:\Development\Website builder\VvvebJs\node_modules\node-sass
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c node scripts/build.js
npm ERR! Building: C:\Program Files\nodejs\node.exe D:\Development\Website builder\VvvebJs\node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp verb cli [
npm ERR! gyp verb cli   'C:\\Program Files\\nodejs\\node.exe',
npm ERR! gyp verb cli   'D:\\Development\\Website builder\\VvvebJs\\node_modules\\node-gyp\\bin\\node-gyp.js',
npm ERR! gyp verb cli   'rebuild',
npm ERR! gyp verb cli   '--verbose',
npm ERR! gyp verb cli   '--libsass_ext=',
npm ERR! gyp verb cli   '--libsass_cflags=',
npm ERR! gyp verb cli   '--libsass_ldflags=',
npm ERR! gyp verb cli   '--libsass_library='
npm ERR! gyp verb cli ]
npm ERR! gyp info using node-gyp@3.8.0
npm ERR! gyp info using node@18.15.0 | win32 | x64
npm ERR! gyp verb command rebuild []
npm ERR! gyp verb command clean []
npm ERR! gyp verb clean removing "build" directory
npm ERR! gyp verb command configure []
npm ERR! gyp verb check python checking for Python executable "python2" in the PATH
npm ERR! gyp verb `which` failed Error: not found: python2
npm ERR! gyp verb `which` failed     at getNotFoundError (D:\Development\Website builder\VvvebJs\node_modules\which\which.js:13:12)
npm ERR! gyp verb `which` failed     at F (D:\Development\Website builder\VvvebJs\node_modules\which\which.js:68:19)
npm ERR! gyp verb `which` failed     at E (D:\Development\Website builder\VvvebJs\node_modules\which\which.js:80:29)
npm ERR! gyp verb `which` failed     at D:\Development\Website builder\VvvebJs\node_modules\which\which.js:89:16
npm ERR! gyp verb `which` failed     at D:\Development\Website builder\VvvebJs\node_modules\isexe\index.js:42:5
npm ERR! gyp verb `which` failed     at D:\Development\Website builder\VvvebJs\node_modules\isexe\windows.js:36:5
npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:208:21)
npm ERR! gyp verb `which` failed  python2 Error: not found: python2
npm ERR! gyp verb `which` failed     at getNotFoundError (D:\Development\Website builder\VvvebJs\node_modules\which\which.js:13:12)
npm ERR! gyp verb `which` failed     at F (D:\Development\Website builder\VvvebJs\node_modules\which\which.js:68:19)
npm ERR! gyp verb `which` failed     at E (D:\Development\Website builder\VvvebJs\node_modules\which\which.js:80:29)
npm ERR! gyp verb `which` failed     at D:\Development\Website builder\VvvebJs\node_modules\which\which.js:89:16
npm ERR! gyp verb `which` failed     at D:\Development\Website builder\VvvebJs\node_modules\isexe\index.js:42:5
npm ERR! gyp verb `which` failed     at D:\Development\Website builder\VvvebJs\node_modules\isexe\windows.js:36:5
npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:208:21) {
npm ERR! gyp verb `which` failed   code: 'ENOENT'
npm ERR! gyp verb `which` failed }
npm ERR! gyp verb check python checking for Python executable "python" in the PATH
npm ERR! gyp verb `which` failed Error: not found: python
npm ERR! gyp verb `which` failed     at getNotFoundError (D:\Development\Website builder\VvvebJs\node_modules\which\which.js:13:12)
npm ERR! gyp verb `which` failed     at F (D:\Development\Website builder\VvvebJs\node_modules\which\which.js:68:19)
npm ERR! gyp verb `which` failed     at E (D:\Development\Website builder\VvvebJs\node_modules\which\which.js:80:29)
npm ERR! gyp verb `which` failed     at D:\Development\Website builder\VvvebJs\node_modules\which\which.js:89:16
npm ERR! gyp verb `which` failed     at D:\Development\Website builder\VvvebJs\node_modules\isexe\index.js:42:5
npm ERR! gyp verb `which` failed     at D:\Development\Website builder\VvvebJs\node_modules\isexe\windows.js:36:5
npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:208:21)
npm ERR! gyp verb `which` failed  python Error: not found: python
npm ERR! gyp verb `which` failed     at getNotFoundError (D:\Development\Website builder\VvvebJs\node_modules\which\which.js:13:12)
npm ERR! gyp verb `which` failed     at F (D:\Development\Website builder\VvvebJs\node_modules\which\which.js:68:19)
npm ERR! gyp verb `which` failed     at E (D:\Development\Website builder\VvvebJs\node_modules\which\which.js:80:29)
npm ERR! gyp verb `which` failed     at D:\Development\Website builder\VvvebJs\node_modules\which\which.js:89:16
npm ERR! gyp verb `which` failed     at D:\Development\Website builder\VvvebJs\node_modules\isexe\index.js:42:5
npm ERR! gyp verb `which` failed     at D:\Development\Website builder\VvvebJs\node_modules\isexe\windows.js:36:5
npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:208:21) {
npm ERR! gyp verb `which` failed   code: 'ENOENT'
npm ERR! gyp verb `which` failed }
npm ERR! gyp verb could not find "python". checking python launcher
npm ERR! gyp verb could not find "python". guessing location
npm ERR! gyp verb ensuring that file exists: C:\Python27\python.exe
npm ERR! gyp ERR! configure error
npm ERR! gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
npm ERR! gyp ERR! stack     at PythonFinder.failNoPython (D:\Development\Website builder\VvvebJs\node_modules\node-gyp\lib\configure.js:484:19)
npm ERR! gyp ERR! stack     at PythonFinder.<anonymous> (D:\Development\Website builder\VvvebJs\node_modules\node-gyp\lib\configure.js:509:16)
npm ERR! gyp ERR! stack     at callback (D:\Development\Website builder\VvvebJs\node_modules\graceful-fs\polyfills.js:306:20)
npm ERR! gyp ERR! stack     at FSReqCallback.oncomplete (node:fs:208:21)
npm ERR! gyp ERR! System Windows_NT 10.0.19045
npm ERR! gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "D:\\Development\\Website builder\\VvvebJs\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
npm ERR! gyp ERR! cwd D:\Development\Website builder\VvvebJs\node_modules\node-sass
npm ERR! gyp ERR! node -v v18.15.0
npm ERR! gyp ERR! node-gyp -v v3.8.0
npm ERR! gyp ERR! not ok
npm ERR! Build failed with error code: 1

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\{User}\AppData\Local\npm-cache\_logs\2023-03-13T19_01_04_702Z-debug-0.log

**Comment by givanz** [comment]
I updated `package-json` to work on node v18.15.0 https://github.com/givanz/VvvebJs/commit/25a3540661d68c1e68a80505d3649055546f4448
