### ISSUE TITLE
Great work, is save.js and node provided just to demonstrate simple saving of just existing pages under /demo? 

### ISSUE THREAD

**Issue by fozak** [givanz/VvvebJs#376]
Hi, first of all, great work. 
Question does the  save.js and node provided just to demonstrate simple saving of just existing pages under /demo? 
as the rest functions (like duplicating pages) doesnt work, is it expected behaviour?
the errors when duplicating (from left pane) pages: 
C:\Python312\VvvebJs\VvvebJs>node save.js
Started
TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received undefined
    at Object.writeFileSync (node:fs:2314:5)
    at C:\Python312\VvvebJs\VvvebJs\save.js:17:6
    at Layer.handle [as handle_request] (C:\Python312\VvvebJs\VvvebJs\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Python312\VvvebJs\VvvebJs\node_modules\express\lib\router\route.js:149:13)
    at Route.dispatch (C:\Python312\VvvebJs\VvvebJs\node_modules\express\lib\router\route.js:119:3)
    at Layer.handle [as handle_request] (C:\Python312\VvvebJs\VvvebJs\node_modules\express\lib\router\layer.js:95:5)
    at C:\Python312\VvvebJs\VvvebJs\node_modules\express\lib\router\index.js:284:15
    at Function.process_params (C:\Python312\VvvebJs\VvvebJs\node_modules\express\lib\router\index.js:346:12)
    at next (C:\Python312\VvvebJs\VvvebJs\node_modules\express\lib\router\index.js:280:10)
    at C:\Python312\VvvebJs\VvvebJs\node_modules\body-parser\lib\read.js:137:5

thanks in advance

**Comment by givanz** [comment]
Hi

Thank you.

`save.php` and `save.js` are provided as example endpoints that can be used as a starting point.

The php version is more complete and has duplicate/rename etc implemented, the javascript example has only save page implemented.
